<a href="https://colab.research.google.com/github/prabuddhayogi/ai-with-python/blob/data_visualization/data_visualization.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd, numpy as np, matplotlib.pyplot as plt

In [2]:
df=pd.read_excel("/content/drive/MyDrive/AI-python/lecture10/sales_training_data.xlsx")
df.head(10)

         Date Product  Units  Price
0  2025-01-01  Laptop      2  50000
1  2025-01-02  Mobile      3  20000
2  2025-01-03  Tablet      4  15000
3  2025-01-04  Laptop      1  50000
4  2025-01-05  Mobile      5  20000
5  2025-01-06  Tablet      2  15000
6  2025-01-07  Laptop      3  50000
7  2025-01-08  Mobile      2  20000
8  2025-01-09  Tablet      1  15000
9  2025-01-10  Laptop      4  50000

In [4]:
df.isnull()

     Date  Product  Units  Price
0   False    False  False  False
1   False    False  False  False
2   False    False  False  False
3   False    False  False  False
4   False    False  False  False
5   False    False  False  False
6   False    False  False  False
7   False    False  False  False
8   False    False  False  False
9   False    False  False  False
10  False    False  False  False
11  False    False  False  False
12  False    False  False  False
13  False    False  False  False
14  False    False  False  False
15  False    False  False  False
16  False    False  False  False
17  False    False  False  False
18  False    False  False  False
19  False    False  False  False
20  False    False  False  False
21  False    False  False  False
22  False    False  False  False
23  False    False  False  False
24  False    False  False  False
25  False    False  False  False
26  False    False  False  False
27  False    False  False  False
28  False    False  False  False
29  False    False  False  False

In [6]:
df["Revenue"] = df['Units']*df['Price']

In [7]:
df

          Date Product  Units  Price  Revenue
0   2025-01-01  Laptop      2  50000   100000
1   2025-01-02  Mobile      3  20000    60000
2   2025-01-03  Tablet      4  15000    60000
3   2025-01-04  Laptop      1  50000    50000
4   2025-01-05  Mobile      5  20000   100000
5   2025-01-06  Tablet      2  15000    30000
6   2025-01-07  Laptop      3  50000   150000
7   2025-01-08  Mobile      2  20000    40000
8   2025-01-09  Tablet      1  15000    15000
9   2025-01-10  Laptop      4  50000   200000
10  2025-01-11  Mobile      3  20000    60000
11  2025-01-12  Tablet      5  15000    75000
12  2025-01-13  Laptop      2  50000   100000
13  2025-01-14  Mobile      1  20000    20000
14  2025-01-15  Tablet      3  15000    45000
15  2025-01-16  Laptop      5  50000   250000
16  2025-01-17  Mobile      4  20000    80000
17  2025-01-18  Tablet      2  15000    30000
18  2025-01-19  Laptop      1  50000    50000
19  2025-01-20  Mobile      2  20000    40000
20  2025-01-21  Tablet      4  15000    60000
21  2025-01-22  Laptop      3  50000   150000
22  2025-01-23  Mobile      5  20000   100000
23  2025-01-24  Tablet      1  15000    15000
24  2025-01-25  Laptop      2  50000   100000
25  2025-01-26  Mobile      3  20000    60000
26  2025-01-27  Tablet      5  15000    75000
27  2025-01-28  Laptop      4  50000   200000
28  2025-01-29  Mobile      2  20000    40000
29  2025-01-30  Tablet      3  15000    45000

In [9]:
product_summary = df.groupby('Product')['Revenue'].sum()
print(product_summary)

Product
Laptop    1350000
Mobile     600000
Tablet     450000
Name: Revenue, dtype: int64