<a href="https://colab.research.google.com/github/prabuddhayogi/ai-with-python/blob/pandas/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd, numpy as np

In [ ]:
df=pd.read_excel("/content/drive/MyDrive/AI-python/lecture8/new_python_dataset.xlsx")
df.head(3)

    Name  Python  Ruby  Java  Pearl
0    Ram    50.0  51.0  74.0   40.0
1   Hari    30.5  54.0  65.0   39.0
2  Shyam    49.0  45.0  40.0   55.0

In [ ]:
df.tail(3)

      Name  Python  Ruby  Java  Pearl
16  Victor    85.0  59.0  23.0   98.0
17  Rathor    19.0  63.0  54.0   65.0
18    Andy    25.0  62.1  34.0   99.0

In [ ]:
df.sample()

    Name  Python  Ruby  Java  Pearl
9  Itcha    58.0  42.0  54.6   89.0

In [ ]:
df1=df.head(3)
df1.to_csv("/content/drive/MyDrive/AI-python/lecture8/new_csv.csv")

In [ ]:
df2=pd.read_csv("/content/drive/MyDrive/AI-python/lecture8/new_csv.csv")
df2["Extra"] = df2["Python"]
df2.to_csv("/content/drive/MyDrive/AI-python/lecture8/new_csv.csv")

In [5]:
# Random seed
np.random.seed(42)
# No of rows
num_rows= 100
ids=np.arange(1,num_rows+1)
# Column name
names=np.random.choice(['Alice','Bob','Charlie','David','Eva','Frank','Gaby','Hannah'], size=num_rows)
# Column gender
genders=np.random.choice(['Male','Female'],size=num_rows)
# Height
heights=np.random.randint(140, 201, size=num_rows)
# Weight
weights = np.random.randint(100, 200, size=num_rows)

# Food type
lunch_options= ['Pizza', 'Sandwich', 'Salad', 'Burger', 'Pasta', 'Sushi', 'Rice', 'Beans']
breakfast_options= ['Cereal','Pancakes','Eggs','Bread', 'Milk','Fruit', 'Yogurt']
dinner_options = ['Steak', 'Fish', 'Rice & Veg', 'Pizza','Pasta', 'Burger', 'Milk','Salad']

lunch=np.random.choice(lunch_options, size=num_rows)
breakfast=np.random.choice(breakfast_options, size=num_rows)
dinner=np.random.choice(dinner_options, size=num_rows)

# health habits
exercise=np.random.choice([True,False], size=num_rows)
# any disease
disease=np.random.choice([True,False],size=num_rows)

#Create DataFrame
df = pd.DataFrame({
    'ID': ids,
    'Name':names,
    'Gender':genders,
    'Height': heights,
    'Weight': weights,
    'Lunch': lunch,
    'Breakfast': breakfast,
    'Dinner': dinner,
    'Exercise': exercise,
    'Disease': disease
})

# Save to CSV
df.to_csv("/content/drive/MyDrive/AI-python/lecture8/random_health_dat.csv", index=False)

In [6]:
df.head(10)

,ID,Name,Gender,Height,Weight,Lunch,Breakfast,Dinner,Exercise,Disease
0,1,Gaby,Male,171,131,Beans,Pancakes,Pizza,True,False
1,2,David,Female,178,167,Burger,Cereal,Fish,True,True
2,3,Eva,Female,188,154,Salad,Milk,Salad,False,False
3,4,Gaby,Female,191,174,Salad,Bread,Rice & Veg,False,True
4,5,Charlie,Female,200,155,Sushi,Pancakes,Pasta,True,False
5,6,Hannah,Female,171,116,Rice,Yogurt,Burger,False,False
6,7,Eva,Female,143,137,Sushi,Cereal,Steak,True,False
7,8,Eva,Female,169,123,Sushi,Bread,Pasta,True,True
8,9,Gaby,Female,176,168,Sushi,Milk,Burger,True,True
9,10,Bob,Male,162,197,Sushi,Bread,Pizza,False,False

In [7]:
df.tail(5)

,ID,Name,Gender,Height,Weight,Lunch,Breakfast,Dinner,Exercise,Disease
95,96,Frank,Female,192,107,Pasta,Milk,Fish,True,False
96,97,Bob,Female,183,106,Sandwich,Fruit,Fish,True,True
97,98,David,Female,165,166,Rice,Milk,Burger,True,True
98,99,Frank,Male,171,116,Sandwich,Yogurt,Fish,True,False
99,100,Eva,Male,145,132,Salad,Eggs,Rice & Veg,True,True

In [9]:
df=pd.read_csv("/content/drive/MyDrive/AI-python/lecture8/random_health_dat_new.csv")
df

,ID,Name,Gender,Height,Weight,Lunch,Breakfast,Dinner,Exercise,Disease
0,1,Hari,Male,171.0,131.0,Beans,Pancakes,Pizza,TRUE,FALSE
1,2,David,Male,178.0,167.0,Burger,Cereal,Fish,TRUE,TRUE
2,3,Eva,Female,188.0,154.0,Salad,Milk,Salad,FALSE,FALSE
3,4,Gaby,Female,191.0,174.0,Salad,Bread,Rice & Veg,FALSE,TRUE
4,5,Charlie,Male,200.0,155.0,Sushi,Pancakes,Pasta,TRUE,FALSE
...,...,...,...,...,...,...,...,...,...,...
95,96,Hero,Male,192.0,107.0,Pasta,Milk,Fish,TRUE,FALSE
96,97,Hector,Male,183.0,106.0,Sandwich,Fruit,Fish,TRUE,TRUE
97,98,NaN,Female,165.0,166.0,Rice,Milk,Burger,TRUE,TRUE
98,99,Frank,Male,171.0,116.0,Sandwich,Yogurt,Fish,TRUE,FALSE
99,100,Eva,Female,145.0,132.0,Salad,Eggs,Rice & Veg,TRUE,TRUE

In [11]:
df.loc[0:100,['Name','Gender']].fillna('miss')

       Name  Gender
0      Hari    Male
1     David    Male
2       Eva  Female
3      Gaby  Female
4   Charlie    Male
..      ...     ...
95     Hero    Male
96   Hector    Male
97     miss  Female
98    Frank    Male
99      Eva  Female

[100 rows x 2 columns]

In [13]:
df.fillna('missing')

,ID,Name,Gender,Height,Weight,Lunch,Breakfast,Dinner,Exercise,Disease
0,1,Hari,Male,171.0,131.0,Beans,Pancakes,Pizza,TRUE,FALSE
1,2,David,Male,178.0,167.0,Burger,Cereal,Fish,TRUE,TRUE
2,3,Eva,Female,188.0,154.0,Salad,Milk,Salad,FALSE,FALSE
3,4,Gaby,Female,191.0,174.0,Salad,Bread,Rice & Veg,FALSE,TRUE
4,5,Charlie,Male,200.0,155.0,Sushi,Pancakes,Pasta,TRUE,FALSE
...,...,...,...,...,...,...,...,...,...,...
95,96,Hero,Male,192.0,107.0,Pasta,Milk,Fish,TRUE,FALSE
96,97,Hector,Male,183.0,106.0,Sandwich,Fruit,Fish,TRUE,TRUE
97,98,missing,Female,165.0,166.0,Rice,Milk,Burger,TRUE,TRUE
98,99,Frank,Male,171.0,116.0,Sandwich,Yogurt,Fish,TRUE,FALSE
99,100,Eva,Female,145.0,132.0,Salad,Eggs,Rice & Veg,TRUE,TRUE

In [14]:
df['Height'].fillna(df['Height'].mean())

0     171.0
1     178.0
2     188.0
3     191.0
4     200.0
      ...
95    192.0
96    183.0
97    165.0
98    171.0
99    145.0
Name: Height, Length: 100, dtype: float64

In [15]:
df.loc[(df['Height']<160)&(df['Weight']<180)]

,ID,Name,Gender,Height,Weight,Lunch,Breakfast,Dinner,Exercise,Disease
6,7,Evangelina,Female,143.0,137.0,Sushi,Cereal,Steak,TRUE,FALSE
12,13,Ram,Male,154.0,110.0,Salad,Fruit,Steak,TRUE,TRUE
16,17,Binod,Male,152.0,158.0,Salad,Yogurt,Pizza,FALSE,FALSE
18,19,Aka,Female,146.0,179.0,Pasta,Pancakes,Pizza,TRUE,FALSE
23,24,Kapoor,Male,141.0,135.0,Beans,Eggs,NaN,NaN,FALSE
28,29,Anita,Female,145.0,119.0,Beans,Milk,Burger,TRUE,TRUE
42,43,Bibhuti,Female,140.0,122.0,Sushi,Cereal,Fish,TRUE,TRUE
47,48,Donna,Female,152.0,106.0,Beans,Milk,Pasta,FALSE,FALSE
52,53,Fir,Male,147.0,100.0,Rice,Bread,Milk,TRUE,","
54,55,Host,Male,148.0,111.0,Burger,Yogurt,Steak,TRUE,TRUE
61,62,Iaan,Male,154.0,147.0,Rice,Pancakes,Pizza,TRUE,FALSE
81,82,Mamta,Female,156.0,165.0,Sandwich,Pancakes,Pizza,TRUE,FALSE
84,85,NaN,Female,141.0,179.0,Sandwich,Yogurt,Fish,TRUE,FALSE
85,86,Nanci,Female,141.0,160.0,Sandwich,Pancakes,Pasta,TRUE,TRUE
92,93,zen,Male,140.0,120.0,Sushi,Milk,Salad,TRUE,TRUE
93,94,Zenisha,Female,158.0,147.0,Beans,Yogurt,Pasta,FALSE,FALSE
94,95,NaN,Male,141.0,119.0,Rice,Yogurt,Fish,TRUE,TRUE
99,100,Eva,Female,145.0,132.0,Salad,Eggs,Rice & Veg,TRUE,TRUE